Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -37,6 +37,13 @@ jobs:
     - name: Setup Gradle
       uses: gradle/gradle-build-action@v2
       
+    - name: Create libs directory
+      run: mkdir -p libs
+      
+    - name: Download dependencies
+      run: |
+        curl -L -o libs/AkariLevel.jar https://github.com/cpjinan/AkariLevel/releases/download/v4.0.12/AkariLevel-4.0.12-api.jar || echo "Failed to download AkariLevel.jar"
+      
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
       
